### PR TITLE
feat: allow ignoring lists of components

### PR DESCRIPTION
**Pull request by boredland**
we needed this for an icon component that retrieves string literals. thought it might be useful.

### CODE REVIEW

**Comment by edvardchen** [comment]
I had explained my concern [here](https://github.com/edvardchen/eslint-plugin-i18next/pull/14#issuecomment-583801419) and plz let me know if you have different thoughts.

@boredland

**Comment by boredland** [comment]
There'll always be people ignoring stuff they shouldn't. For us not having component exclusion would mean to add a ignore line for every icon we have. While I would prefer Icon-Components, we currently don't have them and it would be part of a bigger refactoring to change that.

**Comment by edvardchen** [comment]
Well, I understand your situation. And I cannot offer another effective solution for your case. Why not merge your MR?

**Comment by edvardchen** [comment]
release as v4.2.0 @boredland

**Comment by boredland** [comment]
thank you very much 🎉

**Pull request merged**
