### PR TITLE
Add support for ignoreComponentAttribute

### PR DESCRIPTION
**Pull request by pauliuskalv**
Add option to specify specific object's attributes to ignore (for example to only ignore `` alt attribute, but throw an error on other alt attributes)

### CODE REVIEW

**Comment by edvardchen** [comment]
@pauliuskalv plz add at least one testcase for that option

**Comment by ewdicus** [comment]
I would find this helpful. Are there any blockers to merging this PR?

**Comment by edvardchen** [comment]
@ewdicus @pauliuskalv  try the prerelease version v6.0.0-1. I refactored those options with a consistent way

**Comment by ewdicus** [comment]
@edvardchen Thanks for taking another look at the options! Can you give a quick example of how to represent the use case in this PR in the new options format?

As an example for my specific case, I have an `Icon` jsx component that has a `name` attribute which specifies which icon to render. I'd like to allow that attribute for that specific component to be a literal string, but I don't want to allow that for any other jsx attribute called `name`.

Thanks again!

**Comment by edvardchen** [comment]
@ewdicus even in new version, it didn't support that case

But I think you can try
1. ignore the `Icon` component completely

```json
{
  "mode": "all",
  "jsx-components": {
    "include": [],
    "exclude": ["Trans", "Icon"]
  },
}
```
2. try the default behavior by removing custom options, which only validate jsx text elements

**Pull request closed without merging**
