### PR TITLE
Ignore Trans element

### PR DESCRIPTION
**Pull request by JeffreyATW**
Ignores literals within the `Trans` element, which is added by default as it is part of `react-i18next`.

Thanks!

### CODE REVIEW

**Comment by edvardchen** [comment]
I had read [react-i18next](https://github.com/i18next/react-i18next) and **I agree that `eslint-plugin-i18next` should not  yell at it.**

But `ignoreElement` seems to be too extensive that people would abuse it, like, `ignoreElement: ["div"]` almost disable this eslint plugin

So, I prefer to handle it specially that allow people to use `Trans` but don't expose interface for people to customize.

How do you think?

**Comment by JeffreyATW** [comment]
Actually yes, I agree with this. I coded it so only `Trans` would be ignored, but someone else on my team did decide to add `div` to the list of `ignoreElement` a little while ago, and now we have a big cleanup task ahead of us. I'll make the change to disallow `ignoreElement` and explicitly ignore `Trans`.

**Comment by gorillaboy777** [comment]
Hi, can you please tell what is ETA?

**Comment by edvardchen** [comment]
> Hi, can you please tell what is ETA?

So sorry, I'll review it today

**Comment by edvardchen** [comment]
release as v3.7.0

@gorillaboy777 @JeffreyATW

**Pull request merged**
