### PR TITLE
support validate literal strings in vue component

### PR DESCRIPTION
**Pull request by fants613**
related to: [#133 ](https://github.com/edvardchen/eslint-plugin-i18next/issues/133)

### CODE REVIEW

**Comment by fants613** [comment]
@edvardchen  can help to review the design and code changes, if have any concern, pls feel free to let me know

**Comment by edvardchen** [comment]
I'm having a long holiday. Probably will review a couple of weeks later. Btw, you can try your change on real world projects by using package patch, probably you ald knew it

**Comment by fants613** [comment]
> I'm having a long holiday. Probably will review a couple of weeks later. Btw, you can try your change on real world projects by using package patch, probably you ald knew it

got it,thx

**Comment by edvardchen** [comment]
Great job! Never expect it can be bo so smooth! You even make the code more sensible! Thanks @fants613

**Pull request merged**
